apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-demo-cronjob
spec:
  schedule: "CRON_TZ=Asia/Shanghai 53 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: python-demo
            image: python-demo
            imagePullPolicy: Never
            env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
          restartPolicy: OnFailure